module.exports = {
    GPL: 'http://www.gnu.org/licenses/gpl-3.0.en.html',
    LGPL: 'http://www.gnu.org/licenses/lgpl-3.0.en.html',
    MIT: 'https://opensource.org/licenses/MIT',
    Apache: 'http://www.apache.org/licenses/LICENSE-2.0',
    Artistic: 'http://www.perlfoundation.org/artistic_license_2_0',
    Eclipse: 'https://www.eclipse.org/legal/epl-v10.html',
    BSD3: 'https://opensource.org/licenses/BSD-3-Clause',
    BSD2: 'https://opensource.org/licenses/BSD-2-Clause',
    MPL: 'https://www.mozilla.org/en-US/MPL/2.0/',
    'CC BY AU': 'http://creativecommons.org/licenses/by/3.0/au/legalcode',
    'CC BY': 'http://creativecommons.org/licenses/by/4.0/',
    'CC BY-SA AU': 'http://creativecommons.org/licenses/by-sa/3.0/au/',
    'CC BY-SA': 'http://creativecommons.org/licenses/by-sa/4.0/',
    'CC BY-ND AU': 'http://creativecommons.org/licenses/by-nd/3.0/au',
    'CC BY-ND': 'http://creativecommons.org/licenses/by-nd/4.0/',
    'CC BY-NC AU': 'http://creativecommons.org/licenses/by-nc/3.0/au',
    'CC BY-NC': 'http://creativecommons.org/licenses/by-nc/4.0/',
    'CC BY-NC-SA AU': 'http://creativecommons.org/licenses/by-nc-sa/3.0/au',
    'CC BY-NC-SA': 'http://creativecommons.org/licenses/by-nc-sa/4.0/',
    'CC BY-NC-ND AU': 'http://creativecommons.org/licenses/by-nc-nd/3.0/au',
    'CC BY-NC-ND': 'http://creativecommons.org/licenses/by-nc-nd/4.0/',
    'CC0': 'https://creativecommons.org/publicdomain/zero/1.0/',
    'PDM': 'https://creativecommons.org/publicdomain/mark/1.0/'
}
